### ISSUE TITLE
Wordpress lokal einrichten

### ISSUE THREAD

**Issue by julimage** [julimage/LausitzPropan#1]
![lp-screen_1](https://user-images.githubusercontent.com/8132393/44031170-6907e252-9f03-11e8-9299-3cb0352b9259.jpg)

Hier im beigefügten Bild siehst du einen Screenshot, wie die Startseite aussehen sollte, wenn du alles lokal eingerichtet hast. Wie gesagt, es kann durchaus sein, dass bei dir das LP-Logo durch das divi-Logo ersetzt ist und die Abstände der Sektionen größer sind. Habe nicht herausgefunden, warum das nicht in der Datenbank steht bzw. ausgelesen werden kann. Aber vielleicht geht das ja lokal bei dir. Keine Ahnung.

Bislang vorhandene Seiten/Inhalte:
- Startseite
- Über uns
- Produkte
- Submenu Produkte

**Comment by aschle** [comment]
@julimage  Bei mir lokal sieht man das Divi logo und die Fonts fehlen.
Es gibt ein Problem mit dem Pfad: 

![screen shot 2018-08-23 at 23 48 12](https://user-images.githubusercontent.com/883797/44553842-26241300-a72f-11e8-9277-ea3a33309708.png)

Da müsste anstelle von ib-bauwesen localhost stehen.

**Comment by julimage** [comment]
Ich habe aus Versehen schon die geänderte DB in die Dropbox gelegt. Mein Fehler. Jetzt ist die mit localhost drin.
