### ISSUE TITLE
Oberer Balken mit Preisanzeigen

### ISSUE THREAD

**Issue by julimage** [julimage/LausitzPropan#2]
![lp-screen_3](https://user-images.githubusercontent.com/8132393/44031425-48330efc-9f04-11e8-9c3c-b60a349a4c91.jpg)

Was du hier siehst ist noch ein Teil der Designvorlage. Also lediglich ein Bild. Du siehst ja, dass die Webseite nur einen blauen Balken zeigt in dem links oben steht: "Hier müssen dann mal stehen: Gaspreis | Benzinpreis | Onlineshop"

Der obere blaue Balken also muss angepasst werden. Ich habe natürlich keine Ahnung, wie das geht, aber ich vermute, das muss dort eingebaut werden, wo ich auch diese Zeile hingeschrieben habe. Und zwar liegt das in dem Hauptordner unter wp-content > themes > Divi-Child > header.php

Die originale header.php Datei findet du im Divi-Ordner: wp-content > themes >Divi --> dort liegt überhaupt alles vom originalen Divi-Theme, was wir nicht ändern sollten. Aber, man kann alle Dateien wohl als Kopie im Divi-Child Ordner anlegen und verändern, dann nimmt er beim Auslesen diese.

Zusätzliches CSS, was benötigt wird kommt in die wp-content > themes > Divi-Child > style.css (Da ist auch schon etwas drin, was ich dazugefügt habe.)

**Comment by julimage** [comment]
Man kann auf jeden Fall den Gas- und Dieselpreis händisch im backend eintragen, was dann über php ausgelesen wird. Also ich meine damit, man kann global Fields erstellen. Das ist prima. 

Nun habe ich nochmal mit Herrn Linke telefoniert, weil ich nicht mehr wusste, welcher Preis wann aktualisiert wird.

Der Dieselpreis:
* den meldet er an die MTS-K und da gibt es ja eine Schnittstelle bei tankerkönig.de 
* dieser sollte nach Möglichkeit unbedingt automatisch angezeigt werden

Der Gaspreis:
* den meldet er nicht
* Gaspreis muss manuell eingefügt werden (s. global fields oben)
* Gaspreis ändert sich nur sehr selten. Das letzte mal z. B. wurde er vor einem halben Jahr geändert

So, jetzt habe ich ja gestern diese global fields angelegt, aber bislang noch nicht fertig gestellt... Aber in der php ist es schon vermerkt, deshalb zeigt er auch was an. :-)

**Comment by aschle** [comment]
API: https://creativecommons.tankerkoenig.de/

**Comment by vivian-du** [comment]
Zum Verständnis nochmal nachgefragt:
1. Die Dieselpreis-Daten ziehe ich mir über die tankerkönig.de-API/Schnittstelle (automatisiert)
2. Die Gaspreis-Daten werden manuell im Backend eingepflegt
so weit so gut...

Zu 1.
Ich habe mir ein API-Key besorgt und mir die API-Dokumentation auf tankerkönig.de angeschaut. Über die API kann ich die Preise von bis zu 10 Tankstellen abfragen und auf der Website ausgeben. Vermutlich wollen wir auf der Website aber nur das Angebot einer Tankstelle abfragen und anzeigen, richtig? Wie ist der Name dieser Tankstelle?

**Comment by vivian-du** [comment]
> Man kann auf jeden Fall den Gas- und Dieselpreis händisch im backend eintragen, was dann über php ausgelesen wird. Also ich meine damit, man kann global Fields erstellen. Das ist prima.

@julimage  erstellst du die global fields mit einem WP-Plugin?
Falls ja, schick mir bitte den Pluginname. Habe bei einer Suche auf wordpress.org/plugins/search kein solches Plugin gefunden. Außer du meinst das ACF Plugin.

**Comment by julimage** [comment]
**GLOBAL FIELDS**

https://digwp.com/2009/09/global-custom-fields-take-two/

Hier hab ich das her (bereits modifiziert) und es kommt in die funtions.php im Divi-Child Ordner.

Diese Felder ausfüllen kann man dann im backend unter Einstellungen > Kraftstoffpreise

**Comment by julimage** [comment]
**API für Tankstelle**

Die Tankstelle heißt "Dieselmann". Adresse: An der Bundesstraße 2,  04932 OT Prösen

Die findest du, wenn du bei tankerkönig.de bei PLZ/Ort nach "Prösen" suchst. Da gibt es nur die eine. :-)

**Comment by vivian-du** [comment]
**Dieselpreis automatisch laden und anzeigen**

Wert laden
Der Dieselpreis wird autom. aus der API geladen und auf der LP-Website angezeigt.
Das Script dazu "dieselpreis.js", findest du im Divi-Child Ordner. 

Wert auslesen
In der header.php habe ich im top-header das div#api-dieselpreis eingefügt, in dem der Dieselpreis (API-Wert) ausgelesen wird. 

Eventuell noch zu verbessern 
In der aktuellen Lösung wird der Dieselpreis jedes mal neu geladen und ausgelesen, wenn der User z.B. zu einer anderen Seite wechselt. Weil der Wert erst abgeholt wird, tritt hierbei eine minimale Verzögerung auf.

Schau mal, reicht es so?

**Comment by julimage** [comment]
Die Minimale Verzögerung ist wirklich minimal, wenn du das natürlich ohne großen bösen Aufwand hinbekommst, dass sich der Wert irgendwie gemerkt wird und nicht jedes mal neu geladen wird, ist das super. Ansonsten würde ich meinen, machen wir das nur, wenn es den Auftraggeber stört.

So, jetzt könntest du die obere Zeile gern stylen, dann kann ich dem Auftraggeber mal wieder was zeigen und auch die Inhalte eintackern :-) Schaffst du das in den nächsten Tagen? :-)

**Comment by vivian-du** [comment]
Hey! 
Bin nach einigen Tagen Urlaub wieder an den offen Aufgaben dran und melde mich demnächst wieder bei dir.

**Comment by vivian-du** [comment]
Im Commit vom 2. Okt. sind die UMgesetzungen von oberer Balken mit Preisanzeige und unterbrochener Linie.

Der Pfad zu den Icons (Bilder von deinem Screenshot/Designvorlage) /Applications/MAMP/htdocs/LausitzPropan_WP/wp-content/themes/Divi-Child/images

Teste mal und lass mich wissen wie es läuft.

**Comment by julimage** [comment]
OK, cool, läuft soweit, bis auf die unterbrochene Linie... Hast du etwas an der Datenbank gemacht? Also was im backend? Vielleicht erstellst du mir bitte einen neuen Datenbank-Dump? :-)

![bildschirmfoto 2018-10-02 um 10 24 51](https://user-images.githubusercontent.com/8132393/46337307-827f2a00-c62d-11e8-9ed4-343b0894aee0.png)

**Comment by vivian-du** [comment]
Habe dir ein dump an die googlemailadr. geschickt

**Comment by julimage** [comment]
Nachdem ich die DB importiert habe erscheint gar keine Linie mehr. Das ist super merkwürdig. Vielleicht musst du mir doch einmal erklären, wie du das gemacht hast. :-)

![bildschirmfoto 2018-10-02 um 11 57 38](https://user-images.githubusercontent.com/8132393/46342175-62a23300-c63a-11e8-8bd2-7c39d629df91.png)

**Comment by vivian-du** [comment]
mmh...
das bekommen wir hin!
wollen wir das gleich machen? skypen' für dich okay? ansonsten mobil. mein festnetz ist gerade defekt.

**Comment by julimage** [comment]
Sorry jetzt geht es! :-) Wer weiß woran es lag. Eigentlich sollten die Linien zwar bis an den Browserrand (also orange bis links ran und grau bis rechts ran) aber ist jetzt erstmal wurscht :-)

![bildschirmfoto 2018-10-02 um 12 00 42](https://user-images.githubusercontent.com/8132393/46342381-e0fed500-c63a-11e8-8eb2-13913b875864.png)

**Comment by vivian-du** [comment]
skypename: schnibivi

**Comment by vivian-du** [comment]
für den Fall, dass du an die Anpassungen ran möchtest, du findest sie, auf der Über Uns Page im visual Builder unter dritte Row, Design Settings in den beiden Modulen(Grau), 1.Border und 2.Spacing.

**Comment by julimage** [comment]
Ich denke die obere Anzeige ist erstmal erledigt und damit schließe ich.
