### ISSUE TITLE
Trennlinie unterbrechen

### ISSUE THREAD

**Issue by julimage** [julimage/LausitzPropan#3]
![lp-screen_4](https://user-images.githubusercontent.com/8132393/44031843-90ba3dde-9f05-11e8-923d-16f7c39abc74.jpg)

Hier geht es um die Linie(n) unter "Firmenprofil". Im beigefügten Bild siehst du oben den Entwurf und unten so, wie es eben jetzt im Wordpress aussieht. Ich finde es nicht schlimm, aber natürlich wär es besser, wenn es so gehen würde, wie auf dem Entwurf, also so wie im oberen Teil. Nämlich unterbrochen. Ich hab schon bissl was ausprobiert aber nicht das richtige gefunden, was funktioniert.

Aber vielleicht muss man eben mit Einschränkungen leben, wenn man einen Template-Baukasten nutzt....

**Comment by vivian-du** [comment]
Fixed!
Section-Bereich: Design/Border 0px+Padding 0px
Modules-Bereich: Design/Border 3px, farbe + Padding 25px
