### ISSUE TITLE
Gesplittete Linie

### ISSUE THREAD

**Issue by julimage** [julimage/LausitzPropan#5]
Aktuell können wir im backend ja die Linien farblich so trennen, dass wir diese so dargestellt haben, wie auf der "Über uns" Seite. Im Photoshopentwurf haben wir die Linien aber so gestaltet, dass diese jeweils bis an den Browserrand gehen. (s. beigefügtes Bild) – das habe ich mit Hilfe des backends nicht geschafft, habe aber auch keine Idee, wie man es mit CSS hinzufügen schaffen könnte, da die Container ja vielleicht gar nicht so angelegt sind.

@vivian-du hast du eine Idee, ob das einfach möglich ist oder ob das zu kompliziert ist und man dann bei jeder Seite das komplette Divi umschrauben müsste?

![02_unternehmen_a](https://user-images.githubusercontent.com/8132393/46456782-6061e500-c7b0-11e8-9cb9-297edb5a587f.png)

**Comment by vivian-du** [comment]
Es geht im Back End. Habe es probiert. Sieht aber in der mobilen Version nicht toll aus.
Mehr Freitagabend oder Samstag. Bin morgen auf einer Beerdigung.

**Comment by julimage** [comment]
Hi, bist du morgen erreichbar? Dann kannst du mir das gern mal erklären wie es geht und ich schau es mir an :-) Danke.

**Comment by vivian-du** [comment]
Heute geht, aber erst gg 18:00. Okay für dich? Ansonsten erst Dienstag.
Die Lösung finde ich allerdings nicht praktikabel, da sie eine horizontale Scrollbar in den Mobilen Geräten erzeugt. Ich rate zu einer Kompromisslösung wo die Border nicht bis an den Rand gehen werden.

**Comment by julimage** [comment]
Das ist natürlich nicht schön. Dann wird es wohl so werden aber trotzdem interessiert es mich brennend, wie das geht :-) Heut Abend bin ich so ab 20 Uhr da. Ansonsten gern morgen :-)
